FROM golang:1.22-alpine AS build

WORKDIR /server

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /myserver ./cmd/gin

FROM alpine:edge

WORKDIR /server

COPY --from=build /myserver .

EXPOSE 8000

ENTRYPOINT ["./myserver"]