FROM ubuntu

RUN  apt-get update
RUN  apt-get -y install golang-go 
RUN  apt-get install -y ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . ./server

WORKDIR /server/cmd/gin

CMD go run gin.go